### ISSUE TITLE
Create a checklist for release testing

### ISSUE THREAD

**Issue by cpg** [amahi/ios#346]
Create a checklist of the things we need to go over in order to feel confident that the app will be rock solid

**Comment by anubhavpulkit** [comment]
### Launch Screen 
- [ ] Launch Screen Image in different mode(light and dark)
- [ ] Launch Screen Image in different orientaion (Portrait, Landscape)
### Walkthroght 
- [ ] Buttons working(skip and next) at every slide.
- [ ] Page controller action next and previous points.
- [ ] Ui in Portrait, Landscape orientation.
### Login UI
- [ ] Forget button link.
- [ ] Working of show & hide button.
- [ ] Working of Sign in button(without username& password, with only username, with only password and with username & password filled).
- [ ] notification from login button (when the user fills wrong user name or password).
- [ ] Visibility of text field inputs(font size) and title in different iphones and ipads.
### Your HDA UI
- [ ] Number of available HDA
- [ ] Color of available and unavailable HDA card
- [ ] Notification when user tap on unavailable HDA 
- [ ] Number of available HDA label
- [ ] Navigation bar title
- [ ] All above properties in Dark and light mode
### Shares
- [ ] Number of shares
- [ ] Server name label
- [ ] size of share cards
- [ ] Number of shares label
- [ ] Title of the navigation bar and back button
- [ ] working of the back button on the navigation bar
- [ ] All above properties in Dark and light mode
### Server file(Folder)
- [ ] Working of Sort button
- [ ] Dropdown menu when user press sort button(selected and unselected options colors)
- [ ] Working of layout button
- [ ] Changes in UI when user press layout button(with every sort cases)
- [ ] Working of the floaty button(options when the user press floaty button)
- [ ] UI of floaty button options(after button press)
- [ ] Number of folders/files label
- [ ] Title of the navigation bar and back button
- [ ] Test color of every component in both modes(light/dark)
Search 
- [ ] Working of the search button
- [ ] Working of the search bar(after pressing search button)
- [ ] Working of cancel button after a successful search
- [ ] Updation of the navigation bar while user using the search functionality.
- [ ] All above properties in Dark and light mode
- [ ] Test color of every component in both modes(light/dark)
### Server file(File)
- [ ] Test all the cases of server file(Folder)
- [ ] Working of more option button
- [ ] Dropdown menu when user press more option button
- [ ] Working of swipe action( from left to right and right to left)
- [ ] All above properties in Dark and light mode
- [ ] Test color of every component in both modes(light/dark)
### Recent file
- [ ] Working of layout button
- [ ] Working of search bar
- [ ] Working of more option button
- [ ] Dropdown menu when user press more option button
- [ ] Working of swipe action( from left to right and right to left) 
- [ ] Title of the navigation bar
- [ ] Number of files label
- [ ] Test color of every component in both modes(light/dark)
### Offline
- [ ] Test all the cases of Server file
- [ ] Test color of every component in both modes(light/dark)
### Settings
- [ ] Working of connection button
- [ ] Selected connection
- [ ] Working of Clear temporary downloads button
- [ ] Working of Tell a friend button
- [ ] Working of Sign Out button
- [ ] Test color of every component in both modes(light/dark)

**Comment by anubhavpulkit** [comment]
We have to test in
- iPhone SE (2nd gen)
- iPhone 11
- iPhone Xs, Xs Max
- iPhone 8, 8plus
- iPhone SE
- iPad Air
- iPad Pro
with iOS 12 and iOS 13.1

**Comment by cpg** [comment]
Please put the markdown of the checklist into a file called `ReleaseChecklist.md` in the root of the dir and submit a PR. Thanks.
